[book]
authors = ["Giacomo Peretti"]
language = "it"
multilingual = false
src = "src"
title = "Socket in Python - Giacomo Peretti"

[output.html]
default-theme = "latte"
preferred-dark-theme = "mocha"
additional-css = ["./theme/catppuccin.css"]
